[[module.Result]]
= Result

Error handling with the Result type.

[[type.Result]]
== Result

`Result<Ok, Err>` is the type used for returning and propagating errors. It
is a type with the variants, `#ok(Ok)`, representing success and containing
a value, and `#err(Err)`, representing error and containing an error value.

The simplest way of working with `Result`s is to pattern match on them:

For example, given a function `createUser(user : User) : Result<Id, String>`
where `String` is an error message we could use it like so:
```motoko
switch(createUser(myUser)) {
  case #ok(id) Debug.print("Created new user with id: " # id)
  case #err(msg) Debug.print("Failed to create user with the error: " # msg)
}
```

[source,motoko]
----
type Result<Ok, Err> = {#ok : Ok; #err : Err}
----

[[value.equal]]
== equal



[source,motoko]
----
func equal<Ok, Err>(eqOk : (Ok, Ok) -> Bool, eqErr : (Err, Err) -> Bool, r1 : Result<Ok, Err>, r2 : Result<Ok, Err>) : Bool
----

[[value.compare]]
== compare



[source,motoko]
----
func compare<Ok, Err>(compareOk : (Ok, Ok) -> Order.Order, compareErr : (Err, Err) -> Order.Order, r1 : Result<Ok, Err>, r2 : Result<Ok, Err>) : Order.Order
----

[[value.chain]]
== chain

Allows sequencing of `Result` values and functions that return
`Result`'s themselves.
```
func largerThan10(x : Nat) : Result<Nat, Text> =
  if (x > 10) { #ok(x) } else { #err("Not larger than 10.") };

func smallerThan20(x : Nat) : Result<Nat, Text> =
  if (x < 20) { #ok(x) } else { #err("Not smaller than 20.") };

func between10And20(x : Nat) : Result<Nat, Text> =
  chain(largerThan10(x), smallerThan20)

between10And20(15) = #ok(15);
between10And20(9) = #err("Not larger than 10.");
between10And20(21) = #err("Not smaller than 20.");
```

[source,motoko]
----
func chain<R1, R2, Error>(x : Result<R1, Error>, y : R1 -> Result<R2, Error>) : Result<R2, Error>
----

[[value.flatten]]
== flatten

Flattens a nested Result.

```motoko
assert(flatten<Nat, Text>(#ok(#ok(10))) == #ok(10))
assert(flatten<Nat, Text>(#err("Wrong") == #err("Wrong"))
assert(flatten<Nat, Text>(#ok(#err("Wrong")) == #err("Wrong"))
```

[source,motoko]
----
func flatten<Ok, Error>(result : Result<Result<Ok, Error>, Error>) : Result<Ok, Error>
----

[[value.mapOk]]
== mapOk

Maps the `Ok` type/value, leaving any `Error` type/value unchanged.

[source,motoko]
----
func mapOk<Ok1, Ok2, Error>(x : Result<Ok1, Error>, f : Ok1 -> Ok2) : Result<Ok2, Error>
----

[[value.mapErr]]
== mapErr

Maps the `Err` type/value, leaving any `Ok` type/value unchanged.

[source,motoko]
----
func mapErr<Ok, Error1, Error2>(x : Result<Ok, Error1>, f : Error1 -> Error2) : Result<Ok, Error2>
----

[[value.fromOption]]
== fromOption

Create a result from an option, including an error value to handle the `null` case.
```
fromOption(?(x), e) = #ok(x)
fromOption(null, e) = #err(e)
```

[source,motoko]
----
func fromOption<R, E>(x : ?R, err : E) : Result<R, E>
----

[[value.toOption]]
== toOption

Create an option from a result, turning all #err into `null`.
```
fromOption(#ok(x)) = ?x
fromOption(#err(e)) = null
```

[source,motoko]
----
func toOption<R, E>(r : Result<R, E>) : ?R
----

[[value.iterate]]
== iterate

Applies a function to a successful value, but discards the result. Use
`iterate` if you're only interested in the side effect `f` produces.

```
var counter : Nat = 0;
iterate<Nat, Text>(#ok(5), func (x : Nat) { counter += x });
assert(counter == 5);
iterate<Nat, Text>(#err("Wrong"), func (x : Nat) { counter += x });
assert(counter == 5);
```

[source,motoko]
----
func iterate<Ok, Err>(res : Result<Ok, Err>, f : Ok -> ())
----

[[value.isOk]]
== isOk



[source,motoko]
----
func isOk(r : Result<Any, Any>) : Bool
----

[[value.isErr]]
== isErr



[source,motoko]
----
func isErr(r : Result<Any, Any>) : Bool
----

[[value.assertOk]]
== assertOk

Asserts that its argument is an `#ok` result, traps otherwise.

[source,motoko]
----
func assertOk(r : Result<Any, Any>)
----

[[value.assertErr]]
== assertErr

Asserts that its argument is an `#err` result, traps otherwise.

[source,motoko]
----
func assertErr(r : Result<Any, Any>)
----

